name: macOS Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  PROG:         qt-github-actions
  SOURCE_DIR:   ${{github.workspace}}


jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion:   '==3.1.*'
          version:      '6.7.3'
          archives:     'x86_64 qtbase qttools'
          cache:        true

      - name: Build
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              qmake CONFIG+=release ${{env.SOURCE_DIR}}
              make

      - name: Deploy
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              xcrun --show-sdk-path -sdk macosx
              macdeployqt ${{env.PROG}}.app -dmg -no-plugins
              otool -L ${{env.PROG}}.app/Contents/MacOS/${{env.PROG}}

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.PROG}}-${{github.ref_name}}-macos
          path: |
                ${{env.SOURCE_DIR}}/${{env.PROG}}.app
                ${{env.SOURCE_DIR}}/${{env.PROG}}.dmg

      - name: Test
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              ./${{env.PROG}}.app/Contents/MacOS/${{env.PROG}} --version
              rm -rf ${{env.SOURCE_DIR}}/${{env.PROG}}.app
              ls -l /Applications
              echo Attaching DMG
              hdiutil attach ./${{env.PROG}}.dmg
              rm -rf /Applications/${{env.PROG}}.app
              cp -R /Volumes/${{env.PROG}}/${{env.PROG}}.app /Applications
              hdiutil detach /Volumes/${{env.PROG}}
              cd /
              echo "Run: /Applications/${{env.PROG}}.app/Contents/MacOS/${{env.PROG}"
              /Applications/${{env.PROG}}.app/Contents/MacOS/${{env.PROG}} --version


