name: macOS Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  PROG:         qt-github-actions
  SOURCE_DIR:   ${{github.workspace}}


jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get all tags for correct version determination
        run:  |
              git fetch --all --tags -f

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion:   '==3.1.*'
          version:      '5.15.2'
          archives:     'x86_64 qtbase qttools'
          cache:        true
          setup-python: false

      - name: Build
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              pwd
              cd ${{env.SOURCE_DIR}}
              qmake CONFIG+=release ${{env.SOURCE_DIR}}
              make
              
      - name: Deploy
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              mkdir ${{env.PROG}}
              macdeployqt --dir ${{env.PROG}} ${{env.SOURCE_DIR}}/${{env.PROG}}.app -dmg

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.PROG}}-${{github.ref_name}}-macos
          path: ${{env.SOURCE_DIR}}/${{env.PROG}}


